name: Production Deployment

on:
  push:
    branch:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install the dependencies
        run: npm install

      - name: Audit packages
        run: npm audit

      - name: Deployment
        uses: serverless/github-action@master
        with:
          args: deploy --stage prod
        env:
          FUEL_PRICE_QUEUE_URL: ${{ secrets.FUEL_PRICE_QUEUE_URL }}
          FUEL_PRICE_QUEUE_ARN: ${{ secrets.FUEL_PRICE_QUEUE_ARN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}