name: Production Deployment

on:
  push:
    branch:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install the dependencies
        run: npm ci

      - name: Audit packages
        run: npm audit

      - name: Check code lint
        run: npm run lint:check

      - name: Check code style
        run: npm run format:check

      - name: Tests
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install the dependencies
        run: npm ci

      - name: Deployment
        uses: serverless/github-action@master
        with:
          args: deploy --stage prod
        env:
          FUEL_PRICE_QUEUE_URL: ${{ secrets.FUEL_PRICE_QUEUE_URL }}
          FUEL_PRICE_QUEUE_ARN: ${{ secrets.FUEL_PRICE_QUEUE_ARN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}